#!/bin/bash
mv "/app/applet/26-margherita.png" "/app/applet/public/26-margherita.png"
mv "/app/applet/40-iscasdecarne.png" "/app/applet/public/40-iscas-de-carne.png"
mv "/app/applet/42-estrogonofe decarneinverso.png" "/app/applet/public/42-estrogonofe-de-carne-inverso.png"
mv "/app/applet/7up.png" "/app/applet/public/7up.png"
mv "/app/applet/Água.png" "/app/applet/public/agua.png"
mv "/app/applet/Coca Cola Lata.png" "/app/applet/public/coca-cola-lata.png"
mv "/app/applet/Coca Zero Garrafa.png" "/app/applet/public/coca-zero-garrafa.png"
mv "/app/applet/Coca Zero lata.png" "/app/applet/public/coca-zero-lata.png"
mv "/app/applet/Fanta Laranja.png" "/app/applet/public/fanta-laranja.png"
mv "/app/applet/guarana.png" "/app/applet/public/guarana.png"
mv "/app/applet/haineken.png" "/app/applet/public/haineken.png"
mv "/app/applet/Ice Pêssego.png" "/app/applet/public/ice-pessego.png"
mv "/app/applet/Sagres Cerveja.png" "/app/applet/public/sagres-cerveja.png"
mv "/app/applet/Sumol Laranja.png" "/app/applet/public/sumol-laranja.png"
