UPDATE menu_items SET name = '1 - Bacon' WHERE id = 'e-1';
UPDATE menu_items SET name = '2 - Calabresa' WHERE id = 'e-2';
UPDATE menu_items SET name = '3 - Calapiry' WHERE id = 'e-3';
UPDATE menu_items SET name = '4 - Carijó' WHERE id = 'e-4';
UPDATE menu_items SET name = '5 - Carne' WHERE id = 'e-5';
UPDATE menu_items SET name = '6 - Crocante' WHERE id = 'e-6';
UPDATE menu_items SET name = '7 - Fiambre com Queijo' WHERE id = 'e-7';
UPDATE menu_items SET name = '8 - Frango' WHERE id = 'e-8';
UPDATE menu_items SET name = '9 - Frango com Catupiry' WHERE id = 'e-9';
UPDATE menu_items SET name = '10 - Frampalha' WHERE id = 'e-10';
UPDATE menu_items SET name = '11 - Milho' WHERE id = 'e-11';
UPDATE menu_items SET name = '12 - Milho com Bacon' WHERE id = 'e-12';
UPDATE menu_items SET name = '13 - Tradicional' WHERE id = 'e-13';
UPDATE menu_items SET name = '14 - Margherita' WHERE id = 'e-14';
UPDATE menu_items SET name = '15 - Napolitana' WHERE id = 'e-15';
UPDATE menu_items SET name = '16 - Brócolis com Bacon' WHERE id = 'e-16';
UPDATE menu_items SET name = '17 - Carbonara' WHERE id = 'e-17';
UPDATE menu_items SET name = '18 - Peperoni' WHERE id = 'e-18';
UPDATE menu_items SET name = '19 - Rúcula com Tomate Seco' WHERE id = 'e-19';
UPDATE menu_items SET name = '20 - Strogonoff de Carne' WHERE id = 'e-20';
UPDATE menu_items SET name = '21 - Strogonoff de Frango' WHERE id = 'e-21';
UPDATE menu_items SET name = '22 - Queijo' WHERE id = 'e-22';
UPDATE menu_items SET name = '23 - 4 Queijos' WHERE id = 'e-23';
UPDATE menu_items SET name = '24 - 5 Queijos' WHERE id = 'e-24';
UPDATE menu_items SET name = '25 - Banana com Canela' WHERE id = 'e-25';
UPDATE menu_items SET name = '26 - Chocolate Branco' WHERE id = 'e-26';
UPDATE menu_items SET name = '27 - Chocolate Preto' WHERE id = 'e-27';
UPDATE menu_items SET name = '28 - Nutella' WHERE id = 'e-28';
UPDATE menu_items SET name = '29 - MM\' WHERE id = 'e-29';
UPDATE menu_items SET name = '30 - Leite Ninho - Nido' WHERE id = 'e-30';
UPDATE menu_items SET name = '31 - Oreo Chocolate Branco' WHERE id = 'e-31';
UPDATE menu_items SET name = '32 - Oreo Chocolate Preto' WHERE id = 'e-32';
UPDATE menu_items SET name = '33 - Prestígio' WHERE id = 'e-33';
UPDATE menu_items SET name = '34 - Sensação com Nutella' WHERE id = 'e-34';
UPDATE menu_items SET name = '35 - Sensação com Chocolate Branco' WHERE id = 'e-35';
UPDATE menu_items SET name = '36 - Sensação com Chocolate Preto' WHERE id = 'e-36';
UPDATE menu_items SET name = '37 - Surpresa de Uva Verde Chocolate Branco' WHERE id = 'e-37';
UPDATE menu_items SET name = '38 - Surpresa de Uva Verde Chocolate Preto' WHERE id = 'e-38';
UPDATE menu_items SET name = '39 - Triângulo Amoroso' WHERE id = 'e-39';
UPDATE menu_items SET name = '40 - Banana com Nutella' WHERE id = 'e-40';
